//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThuVien.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ThuVien.ServiceReference1.HelloWorldResponse HelloWorld(ThuVien.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ThuVien.ServiceReference1.HelloWorldResponse> HelloWorldAsync(ThuVien.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VND2USD", ReplyAction="*")]
        double VND2USD(double dong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VND2USD", ReplyAction="*")]
        System.Threading.Tasks.Task<double> VND2USDAsync(double dong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VND2EUR", ReplyAction="*")]
        double VND2EUR(double dong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VND2EUR", ReplyAction="*")]
        System.Threading.Tasks.Task<double> VND2EURAsync(double dong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/USD2VND", ReplyAction="*")]
        double USD2VND(double usd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/USD2VND", ReplyAction="*")]
        System.Threading.Tasks.Task<double> USD2VNDAsync(double usd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EUR2VND", ReplyAction="*")]
        double EUR2VND(double eur);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EUR2VND", ReplyAction="*")]
        System.Threading.Tasks.Task<double> EUR2VNDAsync(double eur);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ThuVien.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ThuVien.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ThuVien.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ThuVien.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ThuVien.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ThuVien.ServiceReference1.WebService1Soap>, ThuVien.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ThuVien.ServiceReference1.HelloWorldResponse ThuVien.ServiceReference1.WebService1Soap.HelloWorld(ThuVien.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ThuVien.ServiceReference1.HelloWorldRequest inValue = new ThuVien.ServiceReference1.HelloWorldRequest();
            inValue.Body = new ThuVien.ServiceReference1.HelloWorldRequestBody();
            ThuVien.ServiceReference1.HelloWorldResponse retVal = ((ThuVien.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ThuVien.ServiceReference1.HelloWorldResponse> ThuVien.ServiceReference1.WebService1Soap.HelloWorldAsync(ThuVien.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ThuVien.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            ThuVien.ServiceReference1.HelloWorldRequest inValue = new ThuVien.ServiceReference1.HelloWorldRequest();
            inValue.Body = new ThuVien.ServiceReference1.HelloWorldRequestBody();
            return ((ThuVien.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        public double VND2USD(double dong) {
            return base.Channel.VND2USD(dong);
        }
        
        public System.Threading.Tasks.Task<double> VND2USDAsync(double dong) {
            return base.Channel.VND2USDAsync(dong);
        }
        
        public double VND2EUR(double dong) {
            return base.Channel.VND2EUR(dong);
        }
        
        public System.Threading.Tasks.Task<double> VND2EURAsync(double dong) {
            return base.Channel.VND2EURAsync(dong);
        }
        
        public double USD2VND(double usd) {
            return base.Channel.USD2VND(usd);
        }
        
        public System.Threading.Tasks.Task<double> USD2VNDAsync(double usd) {
            return base.Channel.USD2VNDAsync(usd);
        }
        
        public double EUR2VND(double eur) {
            return base.Channel.EUR2VND(eur);
        }
        
        public System.Threading.Tasks.Task<double> EUR2VNDAsync(double eur) {
            return base.Channel.EUR2VNDAsync(eur);
        }
    }
}
